### ISSUE TITLE
Block after 24 hours

### ISSUE THREAD

**Issue by SiDChik** [ohld/igbot#1159] opened 2019-12-12 19:57 UTC
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Some accounts receive a block after exactly 24 hours. And others can continue to do thousands of actions without a block. What am I missing? Аfter block I get error 429 and no pause for several hours helps. only relogin saves

**Comment by leoccyao** [comment] 2019-12-12 23:25
Likelihood of block depends on account age, speed and randomization of actions.

Not an issue with codebase, better to ask on https://t.me/instabotproject rather than on issues.

**Comment by reliefs** [comment] 2019-12-13 16:03
it's an issue with the codebase.. I am part of the dev team i know where the issue is.. it's in the code.

**Comment by reliefs** [comment] 2019-12-13 16:10
There is no way to make a "mass-solution" for this, so you have to fix it yourself.. Read the issue related to this and the comments.. The fix is in there.

**Comment by yungobiwan** [comment] 2019-12-13 19:54
Hi @reliefs where is the issue in the codebase?

**Comment by reliefs** [comment] 2019-12-13 21:43
by fixing this i will get more issues than benefits, the issue will then just be mass implemented and fixed by ig and i will have to find a new fix.. 

I have done this several times now for months and i never get any help.. I am not interested in fixing it for a time by risking my own fix..

The fix is out there, read the source code and understand it.. It's actually pretty obvious.

**Comment by bruvv** [comment] 2020-01-11 14:51
I am closing this in favor of this post: https://github.com/instagrambot/instabot/issues/1194 please continu the ban discussion there Thanks for the issue btw!

**Closed as completed by bruvv** 2020-01-11 14:51 UTC
