### ISSUE TITLE
Account gets detected as compromised after using bot.watch_users_reels module for a few hours

### ISSUE THREAD

**Issue by null-routed** [ohld/igbot#1195] opened 2020-01-03 15:08 UTC
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### My Issue

Hello everyone, I tried making a quick script to mass view instagram stories. It lasted for about 3 hours and viewed around 10.000 stories, after that, my script was blocked and my account was displaying this message on phone.
![image](https://user-images.githubusercontent.com/55241343/71730500-a2118d80-2e42-11ea-873a-4605f6204080.png)

After resetting my account I've waited 48 hours to make sure I didn't have any rate limits on my account and tried running this script here https://github.com/instagrambot/instabot/blob/master/examples/stories/watch_user_likers_stories.py as I thought I made something wrong on mine.

After running for about 4 hours and viewing about 6500 stories I eventually got the same message.
Here comes my question. Did anyone figure out what are they detecting? Is it the bot/IP or just a rate limit? If there's a rate limit, did anyone find out what's the maximum number of stories you can view in a certain timeframe?
Thank you.

**Comment by fighterii** [comment] 2020-01-08 21:13
@null-routed : little bit off topic, but out of curiosity: how often could you reset the account? I'm scared of hitting the block second time with my main account..

**Comment by imbarismustafa** [comment] 2020-01-10 21:12
I can confirm. At around 10k views I got the same. The account was fresh new and was just testing the feature. I think one must do less than 10k views in 24 hour timeframe instead of just within 4 hours. Will test it soon. How is on your end?

**Comment by null-routed** [comment] 2020-01-10 22:25
@fighterii Sorry for the late reply but I was not somehow notified about your comment. I have received that message about 7 times and my account looks to be still fine.

@imbarismustafa I believe there's a limit to the whole amount of requests you perform to instagram. I tried to start an auto-liking script after I had recovered my account but I got blocked soon after. I didn't have time to investigate further but maybe they are rate-limiting IPs and not auth tokens, that would be good news.

**Comment by imbarismustafa** [comment] 2020-01-11 00:11
@null-routed do you know how to run it with a proxy? I cannot seem to find a way to do it with proxy because it only accepts two arguments and the second arguments is the like source. Any idea?

**Comment by imbarismustafa** [comment] 2020-01-11 00:20
@null-routed do you know how to make it work with proxy? I see the second argument is for target. I tried to modify and add proxy in the bot.login() but no luck.

**Comment by null-routed** [comment] 2020-01-11 00:27
`>>> bot.login(username = my_username, password =my_password, proxy = my_proxy)
True
>>> `
This works for me. Also the proxies I'm using were passed in the ip:port format. Not sure if they support user:pw auth too.

**Comment by null-routed** [comment] 2020-01-11 00:28
@imbarismustafa 
` bot.login(username = my_username, password =my_password, proxy = my_proxy)
 `
This works for me. Also the proxies I'm using were passed in the ip:port format. Not sure if they support user:pw auth too.

**Comment by imbarismustafa** [comment] 2020-01-11 01:41
> @imbarismustafa
> `bot.login(username = my_username, password =my_password, proxy = my_proxy)`
> This works for me. Also the proxies I'm using were passed in the ip:port format. Not sure if they support user:pw auth too.

Thanks but for me doesnt so will look for an alternative. Currently I keep pushing and keep getting AC when viewing stories even after I have modified to a custom device settings. I changed the Instagram version number to the latest from 8th of January but still does not make a difference. Will keep testing.

**Comment by bruvv** [comment] 2020-01-11 13:31
I am closing this in favor of this post: https://github.com/instagrambot/instabot/issues/1194 please continu the ban discussion there Thanks for the issue btw!

**Closed as completed by bruvv** 2020-01-11 13:31 UTC
