### ISSUE TITLE
Timezone is wrong

### ISSUE THREAD

**Issue by YerToffeeRoll** [ohld/igbot#1117] opened 2019-10-31 18:04 UTC
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```Request returns 400 error!
Traceback (most recent call last):
  File "like_example.py", line 22, in <module>
    bot.like_user("352300017")
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\bot\bot.py", line 685, in like_user
    return like_user(self, user_id, amount, filtration)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\bot\bot_like.py", line 210, in like_user
    if not self.check_user(user_id):
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\bot\bot.py", line 958, in check_user
    return check_user(self, user, unfollowing)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\bot\bot_filter.py", line 144, in check_user
    if user_id == str(self.user_id):
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\bot\bot.py", line 315, in user_id
    return self.api.user_id
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\api\api.py", line 578, in user_id
    return self.cookie_dict["ds_user_id"]
KeyError: 'ds_user_id'

```

---

Hey Team.

My question here is how do we change the login process to allow the bot from being blocked to European users? My location and device configs are correct but Instagram blocks me from using the scripts as the timezone is set to something other than my own timezone?

**Comment by leoccyao** [comment] 2019-11-26 22:21
Duplicate of #860 . First check your username and password, if they are correct, you received an instagram checkpoint challenge. Use 
```
bot.login(ask_for_code=True)
```

Also see #1140

**Closed as completed** 2020-01-15 20:49 UTC
