### ISSUE TITLE
1 First test.jpg' is not uploaded.

### ISSUE THREAD

**Issue by auctas** [ohld/igbot#1114] opened 2019-10-31 08:57 UTC
upload:
FOUND: w:834 h:720 r:1.1583333333333334
2019-10-31 08:44:20,213 - INFO - Photo './pics\1 First test.jpg' is not uploaded.

**Comment by leoccyao** [comment] 2019-11-26 22:07
Seems to be a duplicate of #1111 .

**Closed as completed** 2019-11-27 22:18 UTC
